services:
  invest-monitor:
    build:
      context: ..
      dockerfile: docker/Dockerfile.monitor
    container_name: invest-monitor
    restart: unless-stopped

    volumes:
      - ../conf:/app/conf

    env_file:
      - ../.env
    environment:
      - TZ=Asia/Shanghai
  invest-mcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mcp
    container_name: invest-mcp
    restart: unless-stopped

    volumes:
      - ../conf:/app/conf
    ports:
      - 8888:8888

    env_file:
      - ../.env
    environment:
      - TZ=Asia/Shanghai